let {test}=require("@playwright/test")
test.use({
headless:false,
browserName:"chromium"
})
test('Miniproject1',async({page})=>{
await page.goto("https://automationexercise.com")
let sign=await page.getByText('Signup / Login')
await sign.click();
let email=await page.locator('//input[@data-qa="login-email"]')
await email.fill("pavithra_devi91@rediffmail.com")
let passwprd=await page.locator('//input[@data-qa="login-password"]')
await passwprd.fill("Saikutty@123")
//await page.waitForTimeout(3000)
let ok=await page.locator('//button[@data-qa="login-button"]')
await ok.click()
let kids=await page.locator("a[href='#Kids']")
await kids.click()
await page.locator("#Kids").getByText("Dress").click()
//await page.waitForTimeout(3000)
let allen=await page.locator('a[href="/brand_products/Allen Solly Junior"]')
await allen.click()
//await page.waitForTimeout(3000)
let pinkgown=await page.locator('a[href="/product_details/19"]')
await pinkgown.click()
let count=await page.locator("#quantity")
await count.fill('3')
let add=await page.getByText("Add to cart")
await add.click()
let cont=await page.getByText("Continue Shopping")
await cont.click()
let product=await page.locator('a[href="/products"]')
await product.click()
let Search=await page.locator('#search_product')
await Search.fill("fancy green top")
let cart=await page.locator('a[data-product-id="8"]')
await cart.first().click()
let view=await page.locator('a[href="/view_cart"]')
await view.first().click()
let proceed=await page.getByText("Proceed To Checkout")
await proceed.click()
//await page.waitForTimeout(3000)
let placeorder=await page.getByText("Place Order")
await placeorder.click()
let name=await page.locator('//input[@data-qa="name-on-card"]')
await name.fill("D C NAKENTHIRA PRABU ")
let cardname=await page.locator('//input[@data-qa="card-number"]')
await cardname.fill("5243736603635702")
let cvc=await page.locator('//input[@data-qa="cvc"]')
await cvc.fill('686')
await page.waitForTimeout(3000)
let month=await page.locator('//input[@data-qa="expiry-month"]')
await month.fill('04')
let year=await page.locator('//input[@data-qa="expiry-year"]')
await year.fill('2029')
let finish=await page.locator('//button[@data-qa="pay-button"]')
await finish.click()
let download=await page.getByText("Download Invoice")
await download.click()
//await page.waitForTimeout(3000)
let last=await page.locator('a[data-qa="continue-button"]')
await last.click()
//await page.waitForTimeout(3000)
})